### ISSUE TITLE
빨리 제 로또 번호 뽑아주세요

### ISSUE THREAD

**Issue by aromyang** [lee-dong-gi/testcode#1]

**Comment by lee-dong-gi** [comment]
> _No description provided._

ㅋㅋㅋㅋㅋㅋ 침투력 무엇

**Comment by lee-dong-gi** [comment]
핵심은 로또 스팸 전화 떄문에 인식 나락이고 통계 기간 어쩌구 다 거기서 하는 말인데 전화나 문자 올때마다 책상 다 엎어버리고 싶다고 하는말 듣고 접었습니다 ㅠㅠㅠ
